version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
  - name: Run ESLint
    run: |
      yarn run lint
  - name: Run RuboCop
    run: |
      bundle exec rubocop