version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
  - name: Run ESLint
      run: |
        cd frontend
        npm run lint
  - name: Run RuboCop
      run: |
        cd backend
        bundle exec rubocop